# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39dfb65bf7b22fd146b1e2272e6c47aa985557d80e3094811b843823a92126843f9388940f79e5c521ea487bccca56547027e58afeb1aa406aa3b1edea1a56cd

test:
  secret_key_base: 0acba724dd48beec245782de30c7f15aa289ff5203201ea5fb6763f8d475465a2fd932ef440b4719c8339d68b01b5091e61e73c98015b7f0a7c8b24c3908a08e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 39dfb65bf7b22fd146b1e2272e6c47aa985557d80e3094811b843823a92126843f9388940f79e5c521ea487bccca56547027e58afeb1aa406aa3b1edea1a56cd
